classdef FerriteCurrent < Case2
    methods
        function obj = FerriteCurrent(idx, xl, xr, yl, yt, Ln, Rn, Tn, Bn, H_max, N_max, mu_r, J_r)
            % 调用父类构造函数
            obj@Case2(idx, xl, xr, yl, yt, Ln, Rn, Tn, Bn, H_max, N_max, mu_r, J_r);
            syms x y real
            %{
        
            % 沿 x 方向 A_z
            obj.A_zx_expr = symfun( (obj.yt - y) * obj.c_0x + (y - obj.yl) * obj.d_0x + ...
                symsum( ...
                ((obj.c_hx / obj.beta_h) * sinh(obj.beta_h * (obj.yt - y)) / sinh(obj.beta_h * obj.tau_y) + ...
                (obj.d_hx / obj.beta_h) * sinh(obj.beta_h * (y - obj.yl)) / sinh(obj.beta_h * obj.tau_y)) .* ...
                cos(obj.beta_h * (x - obj.xl)), ...
                obj.h, 1, obj.H_max), [x,y]);
            
            % 沿 y 方向 A_z
            obj.A_zy_expr = symfun( -symsum( ...
                ((obj.e_ny / obj.lambda_n) .* cosh(obj.lambda_n * (x - obj.xl)) ./ sinh(obj.lambda_n * obj.tau_x) - ...
                (obj.f_ny / obj.lambda_n) .* cosh(obj.lambda_n * (obj.xr - x)) ./ sinh(obj.lambda_n * obj.tau_x)) .* ...
                sin(obj.lambda_n * (y - obj.yl)), ...
                obj.n, 1, obj.N_max), [x,y]);
            %}
            % 还有一个特解
            
            
            % 沿 x 方向 A_z
            obj.A_zx_expr = symfun( (obj.yt - y) * obj.c_0x + (y - obj.yl) * obj.d_0x + ...
                ((obj.c_hx / obj.beta_h) * sinh(obj.beta_h * (obj.yt - y)) / sinh(obj.beta_h * obj.tau_y) + ...
                (obj.d_hx / obj.beta_h) * sinh(obj.beta_h * (y - obj.yl)) / sinh(obj.beta_h * obj.tau_y)) .* ...
                cos(obj.beta_h * (x - obj.xl)), ...
                [x,y]);
            
            % 沿 y 方向 A_z
            obj.A_zy_expr = symfun(  ...
                -((obj.e_ny / obj.lambda_n) .* cosh(obj.lambda_n * (x - obj.xl)) ./ sinh(obj.lambda_n * obj.tau_x) - ...
                (obj.f_ny / obj.lambda_n) .* cosh(obj.lambda_n * (obj.xr - x)) ./ sinh(obj.lambda_n * obj.tau_x)) .* ...
                sin(obj.lambda_n * (y - obj.yl)), ...
                [x,y]);
        end
    end
end
