classdef NormalAir < Case1
    methods
        function obj = NormalAir(idx, xl, xr, yl, yt, Ln, Rn, Tn, Bn, H_max, N_max, mu_r)
            % 调用父类构造函数
            obj@Case1(idx, xl, xr, yl, yt, Ln, Rn, Tn, Bn, H_max, N_max, mu_r);
            syms x y real
            
            
            obj.A_zx_expr = symfun(  ...
                ( (obj.c_hx ./ obj.beta_h) .* sinh(obj.beta_h .* (obj.yt - y)) ./ sinh(obj.beta_h .* obj.tau_y) ...
                + (obj.d_hx ./ obj.beta_h) .* sinh(obj.beta_h .* (y - obj.yl)) ./ sinh(obj.beta_h .* obj.tau_y) ) ...
                .* sin(obj.beta_h .* (x - obj.xl)), ...
                [x,y]);
            
            % 沿 y 方向的 A_z 分量
            obj.A_zy_expr = symfun(  ...
                ( (obj.e_ny ./ obj.lambda_n) .* sinh(obj.lambda_n .* (obj.xr - x)) ./ sinh(obj.lambda_n .* obj.tau_x) ...
                + (obj.f_ny ./ obj.lambda_n) .* sinh(obj.lambda_n .* (x - obj.xl)) ./ sinh(obj.lambda_n .* obj.tau_x) ) ...
                .* sin(obj.lambda_n .* (y - obj.yl)), ...
                [x,y]);
            
        end
    end
end
